### List all messages
GET http://localhost:3000/messages/


### Create a new message 
POST http://localhost:3000/messages/
content-Type: application/json

{
    "content": "234"
}


### Get a particular message
GET http://localhost:3000/messages/1232